# Generated by Django 2.1.2 on 2018-11-13 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lectureCode', models.CharField(max_length=120)),
                ('profName', models.CharField(max_length=120)),
                ('classNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdated', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticetracker.Course')),
            ],
        ),
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('lastUpdated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseList', models.ManyToManyField(to='noticetracker.CourseCustom')),
                ('ignoreList', models.ManyToManyField(related_name='ignore', to='noticetracker.Article')),
                ('starList', models.ManyToManyField(related_name='star', to='noticetracker.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursecustom',
            name='siteList',
            field=models.ManyToManyField(to='noticetracker.Site'),
        ),
        migrations.AddField(
            model_name='course',
            name='siteList',
            field=models.ManyToManyField(to='noticetracker.Site'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.ManyToManyField(to='noticetracker.LectureTime'),
        ),
    ]
