# Generated by Django 2.1.3 on 2018-12-02 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
