# Generated by Django 2.1.4 on 2018-12-06 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticetracker', '0002_auto_20181202_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecustom',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
