# Generated by Django 2.1.2 on 2018-12-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticetracker', '0004_auto_20181206_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteHref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField(default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='href', to='noticetracker.Site')),
            ],
        ),
    ]
