# Generated by Django 2.1.3 on 2018-12-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticetracker', '0005_sitehref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitehref',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrefs', to='noticetracker.Site'),
        ),
    ]
